import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { Amplify } from 'aws-amplify'
import outputs from '../amplify_outputs.json'
import './index.css'
import App from './App.jsx'

// Point the Amplify libraries at this project's backend (Cognito, AppSync, etc.).
// `amplify_outputs.json` is generated by `npx ampx sandbox` / the deploy build —
// it is gitignored, so you MUST run the sandbox once before `npm run dev`.
Amplify.configure(outputs)

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
